### ISSUE TITLE
ERROR running texei:skinnyprofile:check:  Cannot convert object to primitive value

### ISSUE THREAD

**Issue by jbronssin** [texei/texei-sfdx-plugin#125]
WHEN : 
CI/CD Script (CircleCi) -> `sfdx texei:skinnyprofile:check`

RESULT :  `ERROR running texei:skinnyprofile:check:  Cannot convert object to primitive value`

ENV : 
- `salesforce/salesforcedx:latest-slim`
- Texei Plugin installed v1.17.2

**Comment by jbronssin** [comment]
@FabienTaillon je t'ai fais l'issue (sorry un peu tard)

**Comment by FabienTaillon** [comment]
@jbronssin it should be fixed, can you try again ?

**Comment by jbronssin** [comment]
It is fixed, well done!
