### ISSUE TITLE
Plugin installation warnings

### ISSUE THREAD

**Issue by kakermanis** [texei/texei-sfdx-plugin#14]
Just installed (which completed successfully) but received the following warnings:

```
warning texei-sfdx-plugin > @salesforce/core > @salesforce/ts-sinon > sinon >@sinonjs/formatio > samsam@1.3.0: This package has been deprecated in favour of @sinonjs/samsam
warning "texei-sfdx-plugin > @oclif/command@1.5.18" has unmet peer dependency "@oclif/plugin-help@^2".
Installing plugin texei-sfdx-plugin... installed v0.0.8
```

**Comment by FabienTaillon** [comment]
I've updated all the plugin dependencies, and I'm not getting these errors anymore.
Closing this issue, if you still see them with the latest version ([v1.3.0](https://github.com/texei/texei-sfdx-plugin/releases/tag/v1.3.0)), let me know and I'll reopen the issue.
