### ISSUE TITLE
Error when using sf texei package dependencies install

### ISSUE THREAD

**Issue by agaudoncr** [texei/texei-sfdx-plugin#141]
When running the following command: sf texei package dependencies install -r -k "1:my_password_123123"

I get the following error

    Error: Only json and js message files are allowed, not .md

Steps to reproduce:
npm i -g @salesforce/cli
sf plugins install texei-sfdx-plugin@sf-v2

run the command

**Comment by FabienTaillon** [comment]
You should install via `sf plugins install texei-sfdx-plugin`, the sf-v2 has been merged to the latest branch so don't use this tag anymore.

**Comment by agaudoncr** [comment]
I have also tried sf plugins install texei-sfdx-plugin@latest and got the same result.

I just re tried with `sf plugins install texei-sfdx-plugin` and got the same outcome.

**Comment by FabienTaillon** [comment]
Looks like sfdx scanner got the same issue for someone that was able to solved it by just uninstalling and reinstalling the plugin, could you try that ?
https://github.com/forcedotcom/sfdx-scanner/issues/998

Could you also try running `sf version` to be sure you're running sf v2 ?
