### ISSUE TITLE
Import Issue

### ISSUE THREAD

**Issue by MuppudathiVelu** [texei/texei-sfdx-plugin#142]
### Request Type
Bug

### Problem Description
I am facing the following issue while importing my records from vs code to salesforce org using texei plugin

>![image](https://github.com/texei/texei-sfdx-plugin/assets/78894466/a29de5dd-73fd-409a-9d6d-bd1f4f34e585)

Sf version: @salesforce/cli/2.16.10 win32-x64 node-v18.18.2

Thanks,
[Muppudathi Velu](https://github.com/MuppudathiVelu)

CC:

**Comment by FabienTaillon** [comment]
Could you please give me all steps to reproduce please ?

**Comment by MuppudathiVelu** [comment]
Hi @FabienTaillon.

While I uninstall the SFDX and reinstall it. Then the issue did not occur on my end.

Thanks,
[Muppudathi Velu](https://github.com/MuppudathiVelu)

**Comment by FabienTaillon** [comment]
Great, closing it then.
