### ISSUE TITLE
Support the --securitytype flag

### ISSUE THREAD

**Issue by MarcDBehr** [texei/texei-sfdx-plugin#15]
Starting with v47.0, the package install command will default the --securitytype parameter's from AllUsers to AdminsOnly.

In order to give users to ability to select the desired flag, the texei:package:dependencies:install command should accept and pass along the -securitytype flag and option

**Comment by FabienTaillon** [comment]
Good feedback !
I'll make sure this is updated before Winter '20 goes to Production.

**Comment by FabienTaillon** [comment]
`--securitytype` flag support has been added in the [v1.1.2](https://github.com/texei/texei-sfdx-plugin/releases/tag/v1.1.2) of the plugin.
