### ISSUE TITLE
[dependencies:install] Unable to pass parameter [-t | --upgrade-type UPGRADE-TYPE]

### ISSUE THREAD

**Issue by arafesthain** [texei/texei-sfdx-plugin#153]
Hello, Any plan to allow to pass the standard parameter through texei plugin ? 

Command I used :

 sf texei package dependencies install -a package -r -w 60 **-t DeprecateOnly** --target-org $ORG_ALIAS -k "1: "

Actual Result :

Error (1): Nonexistent flag: -t

Expected Result:
The texei plugin is passing the -t flag to the sf cli without error

**Comment by FabienTaillon** [comment]
I've added it, can you give it a try after running `sf update` and checking that you're running the v2.3.3 of the plugin ?

**Comment by arafesthain** [comment]
hello @FabienTaillon alright, working fine :) thx
