### ISSUE TITLE
Duplicate CPQSetting set import issue

### ISSUE THREAD

**Issue by aviv-stephanvogel** [texei/texei-sfdx-plugin#160]
By using the cpqsettings set command we inspect that there is an issue with duplicate settings.
for example we have to set "Quote Calculator Plugin" and it matches also for "Legacy Quote Calculator Plugin".
The result is that it is not possible to set the value for "Quote Calculator Plugin"

**Comment by FabienTaillon** [comment]
Thanks for the PR.
