### ISSUE TITLE
--json flag no longer working

### ISSUE THREAD

**Issue by stevebuik** [texei/texei-sfdx-plugin#176]
2.7.1

--json had been working until a couple of releases ago, maybe 2.7.0. now....

sf texei:data:import  --inputdir ./data/demo --json

"code": 1,
  "context": "Import",
  "commandName": "Import",
  "message": "Nonexistent flag: --json\nSee more help with --help",
  "name": "Error",
  "status": 1,

the docs still show --json is supported but --help does not. maybe it was accidentally removed?

**Comment by FabienTaillon** [comment]
@stevebuik thanks for reporting it, should be fixed with [v2.8.0](https://github.com/texei/texei-sfdx-plugin/releases/tag/v2.8.0)
