### ISSUE TITLE
Can't use WAIT Flag

### ISSUE THREAD

**Issue by yippie** [texei/texei-sfdx-plugin#18]
When using `texei:package:dependencies:install` and specifying -w 60 or --wait=60 plugin fails with the error:

ERROR running `texei:package:dependencies:install:`  this.flags.wait.trim is not a function

**Comment by FabienTaillon** [comment]
Thanks for letting us know.
This should be fixed now, upgrade to [v1.2.1](https://www.npmjs.com/package/texei-sfdx-plugin/v/1.2.1) to get the patch.
