### ISSUE TITLE
Unable to set an install wait of 0

### ISSUE THREAD

**Issue by JamieBriersSageCom** [texei/texei-sfdx-plugin#19]
Install command accepts wait parameter, but defaults to 10 minutes.  This is different from the default 0 of the underlying sfdx command.  Due to an issue with the ternary statement, passing in a wait of 0 is treated as a false, and the default 10 is applied.

**Comment by FabienTaillon** [comment]
Fixed by your PR, merged and released in [v1.2.2](https://github.com/texei/texei-sfdx-plugin/releases/tag/v1.2.2). Thanks !
