### ISSUE TITLE
dependencies install does not support the --apexcompile flag

### ISSUE THREAD

**Issue by yippie** [texei/texei-sfdx-plugin#26]
By default, the installing an unlocked package compiles all code in an org. There are situations when this is undesirable or will block a deploy (like if two packages change together and leave things in a broken state until both are updated)

Please add support to pass through the --apexcompile flag to change this behavior during dependency install.

**Comment by FabienTaillon** [comment]
Added to [v1.5.1](https://github.com/texei/texei-sfdx-plugin/releases/tag/v1.5.1).
