### ISSUE TITLE
Data:Export commands exports truncate "0" on String field

### ISSUE THREAD

**Issue by mohametso** [texei/texei-sfdx-plugin#30]
The String field CodeTypologie__c equals to "044", during the extract using Data:Export command, the value on the Json file of the object equald to "44". Same for CodeSinistre__c

<img width="1254" alt="image" src="https://user-images.githubusercontent.com/6200344/82028630-319f3680-9696-11ea-8c46-81339b15159f.png">

{
      "attributes": {
        "type": "Correspondance__c",
        "referenceId": "CorrespondanceRef354"
      },
      "Name": "a063N000000uS0n",
      "RecordTypeId": "SousTypeTache",
      "CreatedDate": "2020-05-11T10:55:21.000+0000",
      "CreatedById": "SfdxOrgUser",
      "LastModifiedDate": "2020-05-11T10:55:21.000+0000",
      "LastModifiedById": "SfdxOrgUser",
      "CodePostal__c": null,
      "CodeProduction__c": null,
      "CodeSinistre__c": "31",
      "CodeTypologie__c": "44",
      "Equipe__c": null,
      "LibSousTypeTacheP__c": null,
      "LibSousTypeTacheS__c": "PROCEDURE",
      "LibTypologie__c": "CONCLUSIONS ADVERSE",
      "PGS__c": null,
      "Type__c": "Sinistre",
      "UGSH__c": null,
      "UGSV__c": null
    }

**Comment by FabienTaillon** [comment]
I wasn't able to reproduce.
I created a field of type String with "042" in it, and it was retrieved correctly.
Are you on the latest version of the plugin ?
Are you on Windows ?

**Comment by mohametso** [comment]
I am on Mac OS. 
Just Updated the plugin and running the export again and now it's work well, 
Thank you for the advice, i will update next time before creating an issue :)
