### ISSUE TITLE
Data plan is not being considered

### ISSUE THREAD

**Issue by pa1vasantham** [texei/texei-sfdx-plugin#34]
We could not able to leverage filter part of the dataplan

log shows the data plan is not being considered while building the query

[exportlog.txt](https://github.com/texei/texei-sfdx-plugin/files/4898163/exportlog.txt)

**Comment by FabienTaillon** [comment]
Can you show me which commands you're running with which parameters please ?

**Comment by pa1vasantham** [comment]
Thanks Fabien ,Sure.

Here are the sequence of things i'm doing in the Terminal  VScode.

>>Generating data plan for the Division__c object

`sfdx texei:data:plan:generate --objects Division__c --outputdir ./data`


>>editing the data-plan.json to add the filter

`{
  "excludedFields": [],
  "sObjects": [
    {
      "name": "Division__c",
      "label": "",
      "filters": "Active__c = false",
      "excludedFields": []
    }
  ]
}`

>>exporting the object with the data plan 

`sfdx texei:data:export --objects Division__c --outputdir ./data --dataplan ./data --targetusername pavan.hcp@apostletech.com.isvdev --json --loglevel INFO`

>>Result expected --only 1 record 
>>Actual Result--All records
>>Observations--Dataplan was not being considered

**Comment by FabienTaillon** [comment]
Can you try removing `--objects Division__c` from `sfdx texei:data:export` command ? It's supposed to be either `--objects` or `--dataplan` but not both. I should add a warning for that in the command.

**Comment by pa1vasantham** [comment]
I've give it a try but now export got failed with the error
`sfdx texei:data:export --outputdir ./data -p ./data --targetusername pavan.hcp@apostletech.com.isvdev`
`EISDIR: illegal operation on a directory, read`

**Comment by pa1vasantham** [comment]
++Inputs
`{
    "status": 1,
    "name": "Error",
    "message": "EISDIR: illegal operation on a directory, read",
    "exitCode": 1,
    "commandName": "Export",
    "stack": "Error: EISDIR: illegal operation on a directory, read\nOuter stack:\n    at Function.wrap (C:\\Users\\Pavankumar Vasantham\\AppData\\Local\\sfdx\\node_modules\\@salesforce\\core\\lib\\sfdxError.js:151:27)\n    at Export.catch (C:\\Users\\Pavankumar Vasantham\\AppData\\Local\\sfdx\\node_modules\\@salesforce\\command\\lib\\sfdxCommand.js:255:67)",
    "warnings": []
}`

**Comment by FabienTaillon** [comment]
Ok got it, the doc isn't good.
The `--dataplan` flag is expecting a file, not a path, so it should be something like `--dataplan ./data/data-plan.json`.

**Comment by pa1vasantham** [comment]
Thanks Fabien.
That did the trick.

**Comment by FabienTaillon** [comment]
Cool, I'll add another command example when running `sfdx texei:data:export -h` to make it easier to understand.
