### ISSUE TITLE
Unable to install plugin with latest sfdx image

### ISSUE THREAD

**Issue by yasarshaikh** [texei/texei-sfdx-plugin#41]
I have a cicd pipeline with [salesforce/salesforcedx](https://github.com/forcedotcom/salesforcedx-docker) image.  It is failing from last 2 days. 

Can you please check by installing the plugin with the latest NPM and sfdx.

**Comment by FabienTaillon** [comment]
@yasarshaikh do you have the error message ?
Also, what is the exact docker image you're using ? I had some trouble a few months back, because the salesforcedx:latest image doesn't exist (or at least isn't updated) anymore, see [here](https://trailblazers.salesforce.com/0D53A00004fbQCE).

**Comment by yasarshaikh** [comment]
Docker image - https://hub.docker.com/r/salesforce/salesforcedx/tags

**Comment by yasarshaikh** [comment]
Pasting log from the pipeline ,and tried with custom docker image but it's failing with some NPM issue with version(will try to reproduce with exact error). 


```
$ echo 'y' | sfdx plugins:install texei-sfdx-plugin
 ›   Warning: You acknowledge and agree that the CLI tool may collect usage 
 ›   information, user environment, and crash reports for the purposes of 
 ›   providing services or functions that are relevant to use of the CLI tool 
 ›   and product improvements.
This plugin is not digitally signed and its authenticity cannot be verified. Continue installation y/n?: Finished digital signature check.
Installing plugin texei-sfdx-plugin... yarn add v1.19.1
Installing plugin texei-sfdx-plugin... info No lockfile found.Installing plugin texei-sfdx-plugin... [1/4] Resolving packages...Installing plugin texei-sfdx-plugin... [2/4] Fetching packages...Installing plugin texei-sfdx-plugin... info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
Uploading artifacts for failed job
Uploading artifacts...
WARNING: tests: no matching files                  
ERROR: No files to upload                          
ERROR: Job failed: exit code 1
```

**Comment by FabienTaillon** [comment]
Looks like there was an issue in the CLI that was fixed this morning, have a look [here](https://trailblazers.salesforce.com/0D54S000008HgMF).

I don't know if the docker image is already up to date. Can you try adding an `sfdx update` command just to be sure it's running the latest version of the CLI ?

**Comment by yasarshaikh** [comment]
It resolved now. Thank you for quick response!
