### ISSUE TITLE
Any way to resume sharing calculations?

### ISSUE THREAD

**Issue by kylethornton** [texei/texei-sfdx-plugin#42]
first off, thank you for this tool, it has made many things easier for me. 

I am using the `sfdx texei:sharingcalc:suspend` command and wondering if there is any way to resume sharing calculations?

`sfdx texei:sharingcalc:resume` for example

**Comment by FabienTaillon** [comment]
Thank you for the comment ! :) 
As you guess, we just never took the time to do it.

Thanks for the PR, I'll have a look to it tomorrow ! 👍
