### ISSUE TITLE
Commands ending with Error: EEXIT: 0  ›   Code: EEXIT

### ISSUE THREAD

**Issue by FabienTaillon** [texei/texei-sfdx-plugin#50]
Several commands are ending with `Error: EEXIT: 0 ›   Code: EEXIT`. For instance, just run `sfdx texei:data:import -h`.
Looks like this is somehow linked to the returned object at the end of the command.

**Comment by ImJohnMDaniel** [comment]
@FabienTaillon -- For what it is worth, I am seeing similar behavior on my custom plugins as well.  At least from my experience thus far, these error messages are not causing any direct problems.  At the moment, I have not done an exhaustive investigation into the cause as there have been other higher priority things to take care of. As always, I am happy to collaborate on the investigation or testing.  Just let me know.

**Comment by FabienTaillon** [comment]
Thank you ! Same here, I haven't seen any issue beside the message itself, but wanted to track it somewhere. Just like you, not number 1 priority but I'll have a look when I have some time.

**Comment by FabienTaillon** [comment]
I'll close this one as this is not linked to this plugin but to the CLI itself:
https://github.com/forcedotcom/cli/issues/589
