### ISSUE TITLE
sfdx texei:package:dependencies:install skips installation of default package

### ISSUE THREAD

**Issue by mobilizer** [texei/texei-sfdx-plugin#55]
Since approx 1-2 weeks the  command `sfdx texei:package:dependencies:install --noprompt` skips the installation of the _default package_. It used to be different and everything was installed on our fresh sandboxes.

The command only installs packages under "dependencies" like the "aepmocks" and skips the default "aepcommon":
```
No dependencies found for package directory aep-source/apex-mocks
Package dependencies found for package directory aep-source/apex-common
    04t????????????????? : aepmocks 51.0.0.LATEST
Resolving dependencies... Done.
```

This is the sfdx-project.json:
```
{
    "packageDirectories": [
        {
            "path": "aep-source/apex-mocks",
            "default": false,
            "package": "aepmocks",
            "versionName": "aepmocks Spring 21",
            "versionNumber": "51.0.0.NEXT"
        },
        {
            "path": "aep-source/apex-common",
            "default": true,
            "package": "aepcommon",
            "versionName": "aepcommon Spring 21",
            "versionNumber": "51.0.0.NEXT",
            "dependencies": [
                {
                    "package": "aepmocks",
                    "versionNumber": "51.0.0.LATEST"
                }
            ]
        }
    ],
    "namespace": "",
    "sfdcLoginUrl": "https://login.salesforce.com",
    "sourceApiVersion": "50.0",
    "packageAliases": {
        "aepmocks": "0Ho1?????????????",
        "aepcommon": "0Ho1?????????????",
...
```

Versions:
sfdx-cli/7.92.0 wsl-x64 node-v14.15.3
texei-sfdx-plugin 1.9.3

I haven't found what the expected behaviour of `sfdx texei:package:dependencies:install` should be: install default package or not!? 

I also tried different versions of @salesforce/core without any solution.

**Comment by FabienTaillon** [comment]
Ok we'll have a look. We haven't change anything in this command recently so this is quite weird.

**Comment by mobilizer** [comment]
Thanks Fabien: Maybe there is really an upstream issue. I have one maybe connected finding: that sfdx force:package:version:create, does not create an version alias with the already provided sfdx-project.json. 

```
sfdx force:package:version:list
=== Package Versions [68]
Package Name                Namespace  Version Name                  Version    Subscriber Package Version Id  Alias                      Installation Key  Released  Validation Skipped  Ancestor  Ancestor Version  Branch
──────────────────────────  ─────────  ────────────────────────────  ─────────  ─────────────────────────────  ─────────────────────────  ────────────────  ────────  ──────────────────  ────────  ────────────────  ──────
aepcommon                              aepcommon Spring 21           51.0.0.3   04t???????????????                                        ?????             true      false               N/A       N/A
v
```

**Comment by mobilizer** [comment]
Can anyone confirm this issue? 

Or is it some issue on our Org/Devhub?

**Comment by FabienTaillon** [comment]
@mobilizer Just looked at it, and I don't understand why this was behaving differently before. The command has not changed for 13 months, and the behavior you describe looks like what I expect the command to do.

It explicitly looks for the `dependencies` section ([here](https://github.com/texei/texei-sfdx-plugin/blob/master/src/commands/texei/package/dependencies/install.ts#L93).

Under your dependencies, you only have `aepmocks`, which is why only this one is installed.
It even tells you that nothing was found for the other package:
`No dependencies found for package directory aep-source/apex-mocks`

The goal of this command is, in a development environment (Scratch Org) to install all needed packages. So for instance if you need Conga, CPQ... you would list them under dependencies, and then the repo content would be pushed to the scratch org.

I'm quite surprised this worked differently at anytime.

Your use case is not to install them for development purpose, but on a sandbox for testing purpose ?

**Comment by mobilizer** [comment]
@FabienTaillon Thanks for your reply. Okay, understood the use case: The command `texei:package:dependencies:install` installs everything in "dependencies".

Yes, our use case is the environment setup of a complete project: like scratch orgs for development and sandboxes for integration testing. 

- Can you suggest any (sfdx) plug-in/command to use for setting up scratch orgs and sandboxes based on sfdx-project.json?
- If there is no good command, is this a command which makes sense to be extended in this project? 
- Or do you suggest to install the highest level packages manually?

**Comment by ImJohnMDaniel** [comment]
@mobilizer -- If I am understanding your ask correctly, a suggestion that I would give is to maintain a small DX project to represent the "Happy Soup".  That project would have a packageDirectory specified in the `sfdx-project.json` and would contain anything that is not able to be packaged.  It would also contain all of the dependencies for all of the packages include the latest build version for the project you are referring to.  This way the deployment and setup of an environment or sandbox is managed completely by this project.  Custom plugins like @FabienTaillon's `texei:package:dependencies:install` could be used to install the entire suite of packages with one command.  Does this make sense?

**Comment by mobilizer** [comment]
@ImJohnMDaniel Thanks for your suggestion of using just a Happy Soup `path` with `dependencies`. This works well and sound like a good process for us. 👍 

This is how the sample code looks like now:
```
{
    "packageDirectories": [
        {
            "path": "aep-source/apex-mocks",
            "default": false,
            "package": "aepmocks",
            "versionName": "aepmocks Spring 21",
            "versionNumber": "51.0.0.NEXT"
        },
        {
            "path": "aep-source/apex-common",
            "default": true,
            "package": "aepcommon",
            "versionName": "aepcommon Spring 21",
            "versionNumber": "51.0.0.NEXT",
            "dependencies": [
                {
                    "package": "aepmocks",
                    "versionNumber": "51.0.0.LATEST"
                }
            ]
        },
        {
            "path": "src",
            "default": false,
            "dependencies": [
                {
                    "package": "aepmocks",
                    "versionNumber": "51.0.0.LATEST"
                },
                {
                    "package": "aepcommon",
                    "versionNumber": "51.0.0.LATEST"
                }
            ]
        }
    ],
    "namespace": "",
    "sfdcLoginUrl": "https://login.salesforce.com",
    "sourceApiVersion": "50.0",
    "packageAliases": {
        "aepmocks": "0Ho1?????????????",
        "aepcommon": "0Ho1?????????????",
```

Note: Also VS Code is complaining about a mal formed sfdx-project.json now, package creation and dependencies:install is working well. 

```
Object is missing property package required by property dependencies.
Object is missing property versionNumber required by property dependencies.
```

So this issue can be closed. 'texei:package:dependencies:install' works as expected and also can be used with the above workaround for the CI-use-case. Thanks everyone! :-)

**Comment by FabienTaillon** [comment]
Thanks @ImJohnMDaniel for helping here :)
