### ISSUE TITLE
texei:package:dependencies:install throws error "Cannot read property 'split' of undefined"

### ISSUE THREAD

**Issue by svavahb** [texei/texei-sfdx-plugin#61]
I just found this plugin command which seems perfect for our use case. However, when running it for a scratch org according to the instructions, the command throws the error in the title.
My command: `sfdx texei:package:dependencies:install -k "1:MyPackage1Key 2:MyPackage2Key 3:" -w 30 -u "MyScratchOrgAlias"`

The dependencies part of the sfdx-json looks like this (anonymized):
```
"dependencies": [
  {
    "package": "MyPackage1Name"
    "subscriberPackageVersionId": "04t..."
   },
  {
    "package": "MyPackage2Name"
    "subscriberPackageVersionId": "04t..."
   },
  {
    "package": "MyPackage3Name"
    "subscriberPackageVersionId": "04t..."
   }
]
```

From looking at the code, it looks the issue might be that our format for the sfdx-project file is different from what the command expects. How should I change it to prevent this issue?

**Comment by FabienTaillon** [comment]
I don't think `subscriberPackageVersionId` is valid here.

Looking at the doc [here](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_unlocked_pkg_config_file.htm), Package Id should be directly specified in the `package` attribute:
```
"dependencies": [
  {
    "package": "04t...""
   },
  {
    "package": "04t...""
   },
  {
    "package": "04t...""
   }
]
```

The other option is to specify the Package Id (0Ho) instead of the Package Version Id (04t) but then you'll also have to specify a versionNumber:
```
"dependencies": [
    {
       "package": "0Ho",
       "versionNumber": "4.7.0.LATEST"
    
    },
    {
       "package" : "04t"
    }
]
```

**Comment by svavahb** [comment]
@FabienTaillon Thank you for the response! Interesting, our format is definitely accepted by sfdx when verifying dependencies for package version creation! Not sure why it's not included in the docs :shrug: 

Will for now update our format to work with the plugin, thanks for the help :)

**Comment by FabienTaillon** [comment]
I'll close the issue for now then, if you later find any reference to `subscriberPackageVersionId` in the documentation please reopen this issue and I'll flag it as an enhancement. Thanks !

**Comment by svavahb** [comment]
Will do, thanks!
