### ISSUE TITLE
Does not detect if the package is already installed

### ISSUE THREAD

**Issue by xixiaofinland** [texei/texei-sfdx-plugin#7]
Hi,

Really good DX plugin to manage the dependent packages! Big thumb up!!

If I run `sfdx texei:package:dependencies:install` twice, the command would install the dependent package twice. Shall we expect it detecting package already installed and skip?

**Comment by FabienTaillon** [comment]
Added to [v1.5.1](https://github.com/texei/texei-sfdx-plugin/releases/tag/v1.5.1)!
