### ISSUE TITLE
Add link to documentation on repo and README

### ISSUE THREAD

**Issue by nvuillam** [texei/texei-sfdx-plugin#88]
You've got brand new easy to browse documentation, but there is no link to it from the main repo :)

You can add it in repository "About" section, and at the top of the README :)

![image](https://user-images.githubusercontent.com/17500430/147059455-d4c2e2c2-31b8-419b-b830-a7b85afe99fe.png)

example:

![image](https://user-images.githubusercontent.com/17500430/147059593-2e83bb63-a769-44af-8926-3b22f3da1f72.png)

**Comment by FabienTaillon** [comment]
Done 😉
