### ISSUE TITLE
Sfdx texei commands are not available after linking the plugin in my local

### ISSUE THREAD

**Issue by sharad272** [texei/texei-sfdx-plugin#90]
I have cloned this repository and after going into this repo in my local and linking this plugin I have observed no sfdx texei commands are available. 

Dir\user_id\Documents\sfdx_texei> sfdx texei:skinnyprofile:retrieve --help
 »  Error: command texei:skinnyprofile:retrieve not found
PS Dir\user_id\Documents\sfdx_texei> sfdx plugins
@salesforce/sfdx-scanner 2.12.0
texei-sfdx-plugin 1.14.0 (link) Dir\user_id\Documents\sfdx_texei

Appreciate your help!

**Comment by FabienTaillon** [comment]
Hi, have you run `npm install` before linking it ? What was the output of the link command ?

**Comment by sharad272** [comment]
Yes I have run the **npm install** command before linking the plugin and this was the output after executing the link command.

Dir\User_id\Documents\sfdx_texei> sfdx plugins:link .
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
warning "eslint-config-oclif > eslint-config-xo-space@0.20.0" has incorrect peer dependency "eslint@^5.3.0".
warning " > eslint-plugin-prettier@3.4.1" has unmet peer dependency "prettier@>=1.13.0".
sfdx-cli: linking plugin texei-sfdx-plugin... done

Should I remove package-lock.json?

**Comment by FabienTaillon** [comment]
Can you also run `npm run prepack` ?
I don't think this was a mandatory step before but now I'm getting the same issue as you if I don't run it.

**Comment by sharad272** [comment]
It is working, commands are available now. Thanks Fabien.
